import json

with open('regressao_ultrassom.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# ---- Celula 1: carregar_dados (index 1) ----
nb['cells'][1]['source'] = (
    "import pandas as pd\n"
    "\n"
    "def carregar_dados(caminho: str) -> pd.DataFrame:\n"
    "    \"\"\"\n"
    "    Le o arquivo CSV e retorna um DataFrame bruto.\n"
    "    pandas e usado APENAS para I/O; todos os calculos sao manuais.\n"
    "    \"\"\"\n"
    "    df = pd.read_csv(caminho, encoding='utf-8')\n"
    "    print(f'Registros carregados : {len(df)}')\n"
    "    return df\n"
    "\n"
    "# --- Execucao ---\n"
    "CAMINHO_CSV = 'Dados_Projeto_Imagem_Ultrassom.xlsx.csv'\n"
    "df_bruto = carregar_dados(CAMINHO_CSV)"
)

# ---- Celula 3: filtrar_xy (index 3) ----
nb['cells'][3]['source'] = (
    "def _converter_br_para_float(valor):\n"
    "    \"\"\"Converte '1,23' -> 1.23\"\"\"\n"
    "    if isinstance(valor, str):\n"
    "        return valor.replace(',', '.')\n"
    "    return valor\n"
    "\n"
    "\n"
    "def filtrar_xy(df: pd.DataFrame):\n"
    "    \"\"\"\n"
    "    Y = PESO\n"
    "    X = IDADE + medidas de ultrassom (AOL, COL, POL, RATIO, EGE, MOL, EC)\n"
    "        + medidas morfometricas a partir de AC.\n"
    "    Remove colunas com mais de 50 pct de NaN e linhas com NaN restante.\n"
    "    Retorna: X (lista de listas), y (lista), nomes das features.\n"
    "    \"\"\"\n"
    "    col_y = 'PESO'\n"
    "    cols_candidatas_x = [\n"
    "        'IDADE',\n"
    "        'AOL (cm\u00b2)', 'COL (cm)', 'POL (cm)', 'RATIO (cm)',\n"
    "        'EGE (mm)', 'MOL', 'EC',\n"
    "        'AC', 'AG', 'CC', 'AP', 'P.C', 'CT', 'CO', 'CCAB',\n"
    "        'LR', 'LCAB', 'LIL', 'LIS', 'Cga', 'Cper', 'PerPe', 'Ccau',\n"
    "        'DC', 'CE'\n"
    "    ]\n"
    "    cols_x = [c for c in cols_candidatas_x if c in df.columns]\n"
    "    subset = df[[col_y] + cols_x].copy()\n"
    "    for col in subset.columns:\n"
    "        subset[col] = subset[col].apply(_converter_br_para_float)\n"
    "        subset[col] = pd.to_numeric(subset[col], errors='coerce')\n"
    "    limite_nan = 0.5 * len(subset)\n"
    "    cols_densas = [c for c in cols_x if subset[c].isna().sum() <= limite_nan]\n"
    "    removidas = set(cols_x) - set(cols_densas)\n"
    "    if removidas:\n"
    "        print(f'Colunas removidas (>50% NaN): {removidas}')\n"
    "    cols_x = cols_densas\n"
    "    subset = subset[[col_y] + cols_x].dropna()\n"
    "    print(f'Amostras apos limpeza : {len(subset)}')\n"
    "    print(f'Features selecionadas : {cols_x}')\n"
    "    y = subset[col_y].tolist()\n"
    "    X = subset[cols_x].values.tolist()\n"
    "    return X, y, cols_x\n"
    "\n"
    "\n"
    "# --- Execucao ---\n"
    "X_bruto, y, COLS_X = filtrar_xy(df_bruto)\n"
    "print(f'\\nPrimeiro valor y: {y[0]}')"
)

# ---- Celula 9: regressao_linear com regularizacao (index 9) ----
nb['cells'][9]['source'] = (
    "# --- Operacoes de Algebra Linear (implementacao manual) ---\n"
    "\n"
    "def _adicionar_bias(X):\n"
    "    \"\"\"Adiciona coluna de 1s (termo independente b0).\"\"\"\n"
    "    return [[1.0] + row[:] for row in X]\n"
    "\n"
    "def _transpor(M):\n"
    "    \"\"\"Transpoe matriz M.\"\"\"\n"
    "    n_lin, n_col = len(M), len(M[0])\n"
    "    return [[M[i][j] for i in range(n_lin)] for j in range(n_col)]\n"
    "\n"
    "def _mult_mat(A, B):\n"
    "    \"\"\"Multiplicacao de matrizes A x B - manual.\"\"\"\n"
    "    n, m, p = len(A), len(B[0]), len(B)\n"
    "    C = [[0.0]*m for _ in range(n)]\n"
    "    for i in range(n):\n"
    "        for j in range(m):\n"
    "            s = 0.0\n"
    "            for k in range(p):\n"
    "                s += A[i][k] * B[k][j]\n"
    "            C[i][j] = s\n"
    "    return C\n"
    "\n"
    "def _inverter_gauss(M):\n"
    "    \"\"\"\n"
    "    Inversao por Eliminacao de Gauss-Jordan com pivotamento parcial.\n"
    "    Implementada 100% manualmente.\n"
    "    \"\"\"\n"
    "    n = len(M)\n"
    "    aug = [M[i][:] + [1.0 if i==j else 0.0 for j in range(n)] for i in range(n)]\n"
    "    for col in range(n):\n"
    "        max_row = max(range(col, n), key=lambda r: abs(aug[r][col]))\n"
    "        aug[col], aug[max_row] = aug[max_row], aug[col]\n"
    "        pivo = aug[col][col]\n"
    "        if abs(pivo) < 1e-12:\n"
    "            raise ValueError('Matriz singular.')\n"
    "        for j in range(2*n):\n"
    "            aug[col][j] /= pivo\n"
    "        for row in range(n):\n"
    "            if row != col:\n"
    "                f = aug[row][col]\n"
    "                for j in range(2*n):\n"
    "                    aug[row][j] -= f * aug[col][j]\n"
    "    return [aug[i][n:] for i in range(n)]\n"
    "\n"
    "def _mult_mat_vec(M, v):\n"
    "    \"\"\"Multiplica matriz M por vetor v - manual.\"\"\"\n"
    "    return [sum(M[i][j]*v[j] for j in range(len(v))) for i in range(len(M))]\n"
    "\n"
    "def _regularizar_XtX(XtX, lam=1e-4):\n"
    "    \"\"\"\n"
    "    Regularizacao de Tikhonov (Ridge): XtX_reg = XtX + lambda*I\n"
    "    Evita singularidade quando features sao correlacionadas. Manual.\n"
    "    \"\"\"\n"
    "    n = len(XtX)\n"
    "    reg = [row[:] for row in XtX]\n"
    "    for i in range(n):\n"
    "        reg[i][i] += lam\n"
    "    return reg\n"
    "\n"
    "\n"
    "def regressao_linear(X_treino, y_treino, lam=1e-4):\n"
    "    \"\"\"\n"
    "    Equacao Normal com regularizacao Ridge:\n"
    "        beta = (XtX + lambda*I)^-1 * Xty\n"
    "    Algebra linear 100% manual.\n"
    "    \"\"\"\n"
    "    X_b     = _adicionar_bias(X_treino)\n"
    "    Xt      = _transpor(X_b)\n"
    "    XtX     = _mult_mat(Xt, X_b)\n"
    "    XtX_reg = _regularizar_XtX(XtX, lam)\n"
    "    XtXi    = _inverter_gauss(XtX_reg)\n"
    "    Xty     = _mult_mat_vec(Xt, y_treino)\n"
    "    beta    = _mult_mat_vec(XtXi, Xty)\n"
    "    print(f'Modelo treinado: {len(beta)} coef (b0 + {len(beta)-1} pesos) | lambda={lam}')\n"
    "    return beta\n"
    "\n"
    "def prever(X, beta):\n"
    "    \"\"\"Predicoes y_hat = X * beta.\"\"\"\n"
    "    X_b = _adicionar_bias(X)\n"
    "    return [sum(X_b[i][j]*beta[j] for j in range(len(beta))) for i in range(len(X_b))]\n"
    "\n"
    "\n"
    "# --- Execucao ---\n"
    "BETA = regressao_linear(X_treino, y_treino)"
)

with open('regressao_ultrassom.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print('Notebook atualizado com sucesso!')
